name: e2e tests - gpu

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MACHINE_USER_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout pull request HEAD commit instead of merge commit - needed to get correct Docker tag commit SHA
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies (python)
        run: |
          pip install -r requirements.lock
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag Docker image with latest commit hash
      - name: Set Docker tag
        id: set_docker_tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)-gpu" >> $GITHUB_ENV

      - name: Build docker images
        run: make tag=$DOCKER_TAG build-gpu

      - name: Publish docker images
        run: make tag=$DOCKER_TAG publish

      - name: Run e2e node tests on monorepo
        run: gh workflow run infernet_node_tests.yaml -R ritual-net/infernet-monorepo-internal --ref main -f docker-tag=$DOCKER_TAG

      - name: Run e2e service tests on monorepo
        run: gh workflow run infernet_services_tests.yaml -R ritual-net/infernet-monorepo-internal --ref main -f docker-tag=$DOCKER_TAG
